name: Test

on:
  push:
    branches:
      - ci/test
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        electron-version:
          - 35
          - 36
          - 37
        node-version:
          - '22.12.x'
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
          # TODO(dsanders11: Enable these once we fix tests on those platforms in CI
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Configure Ubuntu
        if: contains(matrix.os, 'ubuntu')
        shell: bash
        run: |-
          # Setup a virtual display for Electron tests
          sudo apt install -y xvfb
          sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

          # Workaround for Electron AppImage apps failing to initialize on Ubuntu  due to AppArmor restrictions
          # Disables unprivileged user namespaces restriction to allow Electron apps to run
          # Reference: https://github.com/electron/electron/issues/42510
                     : https://github.com/electron-userland/electron-builder/issues/8440
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Electron
        run: npm install "electron@${{ matrix.electron-version }}"
      # TODO(dsanders11): Enable this once we get a clean lint state on `main`
      # - name: Lint
      #   run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
